# -*- coding: utf-8 -*-
"""databds_notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ph2vcnPehP1gvSb74j7-d2Mi-KWPq9rj

# **PHÂN TÍCH BẤT ĐỘNG SẢN DATA**

1.   Mục danh sách
2.   Mục danh sách

**ĐỌC VĂN BẢN **
"""

import pandas as pd
import numpy as np

file_path = '/content/databds_processed.xlsx'
data = pd.read_excel(file_path, sheet_name=None)
print(data.keys())

df_canho = pd.read_excel(file_path, sheet_name='Căn hộ')
df_diachi = pd.read_excel(file_path, sheet_name='Địa chỉ')
df_phaply = pd.read_excel(file_path, sheet_name='Pháp Lý ')
df_huong = pd.read_excel(file_path, sheet_name='Hướng nhà')

df_merge = df_canho.merge(df_diachi, on='Mã Địa Chỉ', how='left')
df_merge = df_merge.merge(df_huong, on='Mã Căn Hộ', how='left')
df_merge = df_merge.merge(df_phaply, on='Mã Địa Chỉ', how='left')

df_merge.head()

df_merge.info()
df_merge.describe()
df_merge.isna().sum()

"""# **EDA – Khám phá dữ liệu**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,5))
sns.histplot(df_merge['Mức giá'], kde=True)
plt.title('Phân phối giá (Mức giá)')
plt.xlabel('Mức giá')
plt.ylabel('Tần suất')
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(df_merge['Mức giá'], kde=True)
plt.title('Phân phối giá (Mức giá)')
plt.xlabel('Mức giá')
plt.ylabel('Tần suất')
plt.xlim(0, 50)   # Chỉ hiển thị từ 0 đến 100
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(df_merge['Diện Tích'], df_merge['Mức giá'])
plt.title('Giá theo diện tích')
plt.xlabel('Diện tích (m2)')
plt.ylabel('Mức giá')
plt.show()

plt.figure(figsize=(10,6))
numeric_df = df_merge.select_dtypes(include=['int64','float64'])
sns.heatmap(numeric_df.corr(), annot=True, cmap='Blues')
plt.title('Ma trận tương quan')
plt.show()

"""Mức giá trong phân phối không lệch mạnh, ít outliers.
Số lượng quan hệ phi tuyến không tốt thì mô hình tuyến tính dễ thất bại. Ưu tiên Tree-based.  

-> Cụ thể làm cộng cụ định giá

**Feature Creation – Tạo đặc trưng mới**
"""

# 1. Đổi đơn vị GIÁ từ "tỷ" → "triệu/m²" (rất quan trọng để mô hình học tốt)
df_merge['Mức giá (triệu)'] = df_merge['Mức giá'] * 1000                    # thành triệu
df_merge['gia/m2'] = df_merge['Mức giá (triệu)'] / df_merge['Diện Tích']

df_merge['log_gia/m2'] = np.log1p(df_merge['gia/m2'])

# 2. Fix HƯỚNG NHÀ bị NaN
map_huong = {
    'Bắc': 0,
    'Đông': 90,
    'Tây': 270,
    'Nam': 180,
    'Đông - Bắc': 45,
    'Đông - Nam': 135,
    'Tây - Nam': 225,
    'Tây - Bắc': 315
}

df_merge['huong_deg'] = df_merge['Hướng Nhà'].map(map_huong).fillna(-1)

df_merge['huong_sin'] = np.sin(np.deg2rad(df_merge['huong_deg']))
df_merge['huong_cos'] = np.cos(np.deg2rad(df_merge['huong_deg']))

good_dirs = ['Đông', 'Đông Nam', 'Đông-Nam', 'Nam']
df_merge['good_direction'] = df_merge['Hướng Nhà'].str.contains('|'.join(good_dirs), case=False, na=False).astype(int)


# Kiểm tra kết quả
print("Các feature mới tạo:")
cols_to_show = ['Mức giá', 'Mức giá (triệu)', 'Diện Tích', 'gia/m2',
                'log_gia/m2', 'Hướng Nhà', 'huong_deg', 'good_direction']
display(df_merge[cols_to_show].head(10))

# Xem không còn NaN ở các cột quan trọng nữa
print("\nSố lượng NaN sau khi xử lý:")
print(df_merge[['gia/m2', 'huong_deg', 'huong_sin', 'huong_cos']].isna().sum())

!pip install category-encoders -q

from category_encoders import TargetEncoder
import numpy as np

df_merge['quan_encoded'] = TargetEncoder(smoothing=10).fit_transform(
    df_merge['Quận/Huyện'].astype(str), df_merge['log_gia/m2']
)

df_merge['total_rooms'] = df_merge['Số Phòng Ngủ'] + df_merge['Số Toilet'] + df_merge['Số Tầng']
df_merge[['Quận/Huyện', 'quan_encoded', 'total_rooms']].head()

from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
import numpy as np

features = ['Diện Tích','Số Tầng','Số Phòng Ngủ','Số Toilet',
            'gia/m2','log_gia/m2','total_rooms','quan_encoded',
            'huong_sin','huong_cos','good_direction']

X = df_merge[features].fillna(-999)
y = df_merge['log_gia/m2']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LGBMRegressor(n_estimators=800, learning_rate=0.03, max_depth=8,
                      num_leaves=64, random_state=42, verbose=-1)
model.fit(X_train, y_train)

pred = model.predict(X_test)
print(f"R²     = {r2_score(y_test, pred):.4f}")
print(f"MAE    = {mean_absolute_error(np.expm1(y_test), np.expm1(pred)):.1f} triệu")
print(f"MAPE   = {np.mean(np.abs((np.expm1(y_test) - np.expm1(pred)) / np.expm1(y_test))):.1%}")

#XGBOOST
!pip install xgboost shap -q

import xgboost as xgb
import shap
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

features = ['Diện Tích','Số Tầng','Số Phòng Ngủ','Số Toilet',
            'gia/m2','log_gia/m2','total_rooms','quan_encoded',
            'huong_sin','huong_cos','good_direction']

X = df_merge[features].fillna(-999)
y = df_merge['log_gia/m2']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = xgb.XGBRegressor(
    n_estimators      = 1200,
    learning_rate     = 0.02,
    max_depth         = 8,
    min_child_weight  = 3,
    subsample         = 0.85,
    colsample_bytree  = 0.8,
    gamma             = 0.1,
    random_state      = 42,
    tree_method       = 'hist',
    n_jobs            = -1
)

model.fit(X_train, y_train, verbose=False)

pred = model.predict(X_test)
r2   = r2_score(y_test, pred)
mae  = mean_absolute_error(np.expm1(y_test), np.expm1(pred))
mape = np.mean(np.abs((np.expm1(y_test) - np.expm1(pred)) / np.expm1(y_test))) * 100

print("XGBOOST KẾT QUẢ")
print(f"R²     = {r2:.4f}  ")
print(f"MAE    = {mae:.1f} triệu")
print(f"MAPE   = {mape:.2f}%  ")

#CHẠY 5 INSIGHT THỰC TẾ, "

import shap
import matplotlib.pyplot as plt
import numpy as np

# Top yeu to quyet dinh gia
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test)

plt.figure(figsize=(10,6))
shap.summary_plot(shap_values, X_test, plot_type="bar", max_display=12, show=False)
plt.title("Top yếu tố quyết định giá nhà")
plt.tight_layout()
plt.show()

use_log = 'log_price' in df_merge.columns or (hasattr(y, 'name') and y.name == 'log_price')
def predict_mean(df_mod):
    pred = model.predict(df_mod)
    return np.expm1(pred).mean() if use_log else pred.mean()

base_price = predict_mean(X_test)
col_area   = 'Diện Tích'
col_quan   = 'quan_encoded'
col_dir    = 'good_direction'
col_rooms  = 'total_rooms'
col_ppm2   = 'gia/m2'

# 5 INSIGHT THỰC TẾ
insights = []

# 1. Quận tốt
high_quan = predict_mean(X_test.assign(**{col_quan: X_test[col_quan].quantile(0.9)}))
insights.append(f"Quận/Huyện tốt (top 10%) → giá cao hơn {(high_quan/base_price-1)*100:.1f}%")

# 2. Hướng tốt
good_dir_price = predict_mean(X_test.assign(**{col_dir: 1}))
insights.append(f"Hướng Đông/Đông-Nam → giá cao hơn {(good_dir_price/base_price-1)*100:.1f}%")

# 3. Tăng 50% diện tích
large_area = predict_mean(X_test.assign(**{col_area: X_test[col_area] * 1.5}))
insights.append(f"Tăng 50% diện tích → giá tăng {(large_area/base_price-1)*100:.1f}%")

# 4. Nhiều phòng
top_rooms = predict_mean(X_test.assign(**{col_rooms: X_test[col_rooms].quantile(0.9)}))
insights.append(f"Nhà nhiều phòng (top 10%) → giá cao hơn {(top_rooms/base_price-1)*100:.1f}%")

# 5. Vị trí đắc địa
premium = predict_mean(X_test.assign(**{col_ppm2: X_test[col_ppm2].quantile(0.9)}))
insights.append(f"Vị trí đắc địa (giá/m² top 10%) → giá cao hơn {(premium/base_price-1)*100:.1f}%")

print("\n" + "="*85)
print("          5 BUSINESS INSIGHT THỰC TẾ TỪ DỮ LIỆU CỦA BẠN")
print("="*85)
for i, text in enumerate(insights, 1):
    print(f"{i}. {text}")
print("="*85)

# SO SÁNH LightGBM vs XGBoost
!pip install lightgbm xgboost shap -q

import lightgbm as lgb
import xgboost as xgb
import numpy as np
import matplotlib.pyplot as plt
import shap
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
plt.rcParams['font.size'] = 12

features = ['Diện Tích','Số Tầng','Số Phòng Ngủ','Số Toilet',
            'gia/m2','log_gia/m2','total_rooms','quan_encoded',
            'huong_sin','huong_cos','good_direction']

X = df_merge[features].fillna(-999)
y = df_merge['log_price'] if 'log_price' in df_merge.columns else np.log1p(df_merge['Mức giá (triệu)'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train 2 model
lgb_model = lgb.LGBMRegressor(n_estimators=1000, learning_rate=0.03, max_depth=8,
                              num_leaves=70, subsample=0.8, colsample_bytree=0.8,
                              random_state=42, verbose=-1)
xgb_model = xgb.XGBRegressor(n_estimators=1000, learning_rate=0.03, max_depth=8,
                             subsample=0.8, colsample_bytree=0.8, random_state=42,
                             tree_method='hist', n_jobs=-1)

lgb_model.fit(X_train, y_train)
xgb_model.fit(X_train, y_train, verbose=False)

#Tính metric
def get_metrics(model, name):
    pred = model.predict(X_test)
    y_true = np.expm1(y_test)
    y_pred = np.expm1(pred)
    return {
        'Model': name,
        'R²': r2_score(y_test, pred),
        'MAE (triệu)': mean_absolute_error(y_true, y_pred),
        'MAPE (%)': np.mean(np.abs((y_true - y_pred)/y_true))*100
    }

results = [get_metrics(lgb_model, 'LightGBM'), get_metrics(xgb_model, 'XGBoost')]
df_res = pd.DataFrame(results)

fig = plt.figure(figsize=(20, 12))

# 1. So sánh R², MAE, MAPE
ax1 = plt.subplot(2, 3, 1)
df_res.plot(x='Model', y=['R²'], kind='bar', ax=ax1, color=['#1f77b4', '#ff7f0e'], legend=False)
ax1.set_title('R² (càng cao càng tốt)', fontsize=14, fontweight='bold')
ax1.bar_label(ax1.containers[0], fmt='%.4f')

ax2 = plt.subplot(2, 3, 2)
df_res.plot(x='Model', y=['MAE (triệu)'], kind='bar', ax=ax2, color=['#2ca02c', '#d62728'], legend=False)
ax2.set_title('MAE (càng thấp càng tốt)', fontsize=14, fontweight='bold')
ax2.bar_label(ax2.containers[0], fmt='%.0f')

ax3 = plt.subplot(2, 3, 3)
df_res.plot(x='Model', y=['MAPE (%)'], kind='bar', ax=ax3, color=['#9467bd', '#8c564b'], legend=False)
ax3.set_title('MAPE % (càng thấp càng tốt)', fontsize=14, fontweight='bold')
ax3.bar_label(ax3.containers[0], fmt='%.2f%%')


# In bảng kết quả
print("\SO SÁNH  LightGBM vs XGBoost:")
print(df_res.round(4))

#Decision Tree
from sklearn.tree import DecisionTreeRegressor, plot_tree
import matplotlib.pyplot as plt

dt = DecisionTreeRegressor(max_depth=3, random_state=42)
dt.fit(X_train, y_train)

plt.figure(figsize=(20,10))
plot_tree(dt, feature_names=features, filled=True, rounded=True, fontsize=12,
          impurity=False, proportion=True, precision=1)
plt.title("Decision Tree – Nhánh cụ thể (depth=3)", fontsize=16, fontweight='bold')
plt.show()

print(f"R² của cây này: {r2_score(y_test, dt.predict(X_test)):.4f}")

#Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
import matplotlib.pyplot as plt

model_lr = LinearRegression()
model_lr.fit(X_train, y_train)
pred_lr = model_lr.predict(X_test)

plt.figure(figsize=(8,6))
plt.scatter(np.expm1(y_test), np.expm1(pred_lr), alpha=0.6, color='blue', s=40)
plt.plot([0, np.expm1(y_test).max()], [0, np.expm1(y_test).max()], 'r--', lw=2)
plt.xlabel('Giá thực tế (triệu)')
plt.ylabel('Giá dự đoán - Linear Regression (triệu)')
plt.title(f'Linear Regression\nR² = {r2_score(y_test, pred_lr):.4f} | MAE = {mean_absolute_error(np.expm1(y_test), np.expm1(pred_lr)):.0f} triệu')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

